name: main

on:
  push:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: E2E

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Properties
        if: ${{ github.event.repository.fork == false && (github.event.pull_request == null || github.event.pull_request.head.repo.fork == false) }}
        env:
          E2E_CREDENTIALS_BASE64: ${{ secrets.E2E_CREDENTIALS_BASE64 }}
          OKTA_PROPERTIES_BASE64: ${{ secrets.OKTA_PROPERTIES_BASE64 }}
        run: |
          mkdir -p browser-sign-in/src/androidTest/resources/
          echo $E2E_CREDENTIALS_BASE64 | base64 --decode > browser-sign-in/src/androidTest/resources/e2eCredentials.yaml
          echo $OKTA_PROPERTIES_BASE64 | base64 --decode > okta.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests
        run: ./gradlew assembleDebug testDebugUnitTest assembleAndroidTest

      - name: Authenticate Gcloud command line
        if: ${{ github.event.repository.fork == false && (github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'e2e')) }}
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          GOOGLE_SERVICE_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64 }}
        run: ./signInToGcloud.sh && source $HOME/google-cloud-sdk/path.bash.inc && export CLOUDSDK_CORE_DISABLE_PROMPTS=1

      - name: Run End to End Tests
        if: ${{ github.event.repository.fork == false && (github.ref == 'refs/heads/master' || contains(github.event.pull_request.labels.*.name, 'e2e')) }}
        run: ./runTestsInFirebaseTestLab.sh

      - name: Upload Test Failures
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-failures
          path: |
            **/build/reports/tests/
            **/out/failures/
